### PR TITLE
[application] Tiến

### PR DESCRIPTION
**Pull request by tien**
Not sure if my application checks all the boxes, because I'm very new to this space :p (tooling)

But I would like to use this as an opportunity to share what I've been building so far :D

### CODE REVIEW

**Comment by ggwpez** [comment]
>A reactive library for building Substrate front-ends

This sounds very much on-point with the direction of PoToC. Thanks for applying.  
For projects to be considered relevant, they should have some demonstrated usage. Do you know if someone is already using this library?  
Otherwise it could help to either: drive adoption of that lib or helping out other relevant projects from the [mission list](https://github.com/polkadot-tooling-collective/collective/blob/master/mission_list.md).

**Comment by tien** [comment]
> drive adoption of that lib or helping out other relevant projects

My goal basically for putting forward this application ✌️

Not too important whether I'm eligible right now. I want to share what I'm doing, get to know everyone in this space and gain insight/guidance if possible :D

**Comment by tien** [comment]
@ggwpez Have added another WIP tool that I'm currently working on :p

Also, would be great if you can check out my forum post [here](https://forum.polkadot.network/t/reactive-dot-a-reactive-library-for-building-substrate-front-ends/8655) and leave some feedback :D

**Comment by ggwpez** [comment]
Yea nice, i am not a front-end dev myself but it looks like there is good feedback in the Forum 😄

**Comment by tien** [comment]
I've also recently built this:

- Website: https://dotconsole.app/
- Repo: https://github.com/tien/dot-console

Which is a Substrate development console, similar to the [PJS dev tool](https://polkadot.js.org/apps/#/chainstate), but built with PAPI & Reactive DOT instead.

Not sure if this fit the bill of "tooling", or does tooling strictly has to be libraries?

Appreciate any clarification and thanks in advance 😄.

**Comment by wirednkod** [comment]
Nice to see you here @tien .
The DotConsole would not pass the bar of a "tooling" rank, but dotconnect and reactive-dot surely does.

**Review by ggwpez — APPROVED** [review]
Very much appreciated, thanks!

**Pull request merged**
